version: '3.7'
services:
  dev:
    container_name: dev
    build: .
    tty: true
    networks: 
      - dev
    ports: 
      - 8080:8080
      - 80:80
      - 3000:3000
      - 4000:4000
      - 4200:4200
networks:
  dev: